name: Build Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [386, amd64]
        include:
          - arch: 386
            suffix: x86
          - arch: amd64
            suffix: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -v -o "foxmail_password_recovery_${{ matrix.suffix }}.exe" ./main

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 更新到 v4 版本
        with:
          name: foxmail_password_recovery_${{ matrix.suffix }}
          path: foxmail_password_recovery_${{ matrix.suffix }}.exe
          retention-days: 5  # 设置保留时间为5天
